#!/bin/bash

# Complete E2E workflow test
# Tests: Signup → Login → Dashboard → Create Project

echo "================================"
echo "COMPLETE E2E WORKFLOW TEST"
echo "================================"
echo ""

BASE_URL="http://localhost:5000"
TIMESTAMP=$(date +%s%3N)
TEST_EMAIL="testuser${TIMESTAMP}@test.com"
TEST_USERNAME="user$((RANDOM % 10000))"
TEST_PASSWORD="TestPass123"
TEST_DISPLAY="Test User"

echo "Test credentials:"
echo "  Email: $TEST_EMAIL"
echo "  Username: $TEST_USERNAME"
echo "  Password: $TEST_PASSWORD"
echo ""

# STEP 1: Signup
echo "STEP 1️⃣: Testing Signup..."
SIGNUP_RESPONSE=$(curl -s -X POST "$BASE_URL/api/auth/signup" \
  -H "Content-Type: application/json" \
  -d "{
    \"email\": \"$TEST_EMAIL\",
    \"username\": \"$TEST_USERNAME\",
    \"password\": \"$TEST_PASSWORD\",
    \"displayName\": \"$TEST_DISPLAY\"
  }")

echo "Signup Response: $SIGNUP_RESPONSE"
TOKEN=$(echo "$SIGNUP_RESPONSE" | grep -o '"token":"[^"]*' | cut -d'"' -f4)

if [ -z "$TOKEN" ]; then
  echo "❌ Signup failed - no token received"
  exit 1
fi

echo "✅ Signup successful! Token: ${TOKEN:0:20}..."
echo ""

# STEP 2: Get current user
echo "STEP 2️⃣: Testing /auth/me endpoint..."
ME_RESPONSE=$(curl -s -X GET "$BASE_URL/api/auth/me" \
  -H "Authorization: Bearer $TOKEN")

echo "User Info: $ME_RESPONSE"
echo "✅ /auth/me successful"
echo ""

# STEP 3: List projects (should be empty for new user)
echo "STEP 3️⃣: Listing projects (should be empty)..."
PROJECTS_RESPONSE=$(curl -s -X GET "$BASE_URL/api/projects" \
  -H "Authorization: Bearer $TOKEN")

echo "Projects Response: $PROJECTS_RESPONSE"
echo "✅ List projects successful"
echo ""

# STEP 4: Create a project
echo "STEP 4️⃣: Creating a project..."
TOURNAMENT_NAME="E2E Test Chess Championship"
PROJECT_RESPONSE=$(curl -s -X POST "$BASE_URL/api/projects" \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/json" \
  -d "{
    \"name\": \"$TOURNAMENT_NAME\",
    \"slug\": \"e2e-test-chess-championship\",
    \"description\": \"Test tournament website generated by E2E test\",
    \"specification\": {
      \"tournamentName\": \"$TOURNAMENT_NAME\",
      \"date\": \"2026-04-15\",
      \"location\": \"San Francisco, CA\",
      \"description\": \"A complete chess tournament\",
      \"pages\": [\"home\", \"info\", \"register\", \"schedule\", \"players\"],
      \"colorScheme\": \"modern\"
    }
  }")

echo "Project Creation Response: $PROJECT_RESPONSE"
PROJECT_ID=$(echo "$PROJECT_RESPONSE" | grep -o '"project":{"id":"[^"]*' | cut -d'"' -f4)

if [ -z "$PROJECT_ID" ]; then
  echo "❌ Project creation failed"
  exit 1
fi

echo "✅ Project created! Project ID: $PROJECT_ID"
echo ""

# STEP 5: Get the created project
echo "STEP 5️⃣: Retrieving created project..."
GET_PROJECT=$(curl -s -X GET "$BASE_URL/api/projects/$PROJECT_ID" \
  -H "Authorization: Bearer $TOKEN")

echo "Project Details: $GET_PROJECT"
echo "✅ Project retrieval successful"
echo ""

# STEP 6: List projects (should now have 1)
echo "STEP 6️⃣: Listing projects again (should have 1)..."
FINAL_PROJECTS=$(curl -s -X GET "$BASE_URL/api/projects" \
  -H "Authorization: Bearer $TOKEN")

echo "Final Projects: $FINAL_PROJECTS"
echo "✅ Final projects list successful"
echo ""

echo "================================"
echo "✅ ALL TESTS PASSED!"
echo "================================"
echo ""
echo "Workflow verified:"
echo "  ✅ Signup works"
echo "  ✅ Authentication works"
echo "  ✅ Get user info works"
echo "  ✅ List projects works"
echo "  ✅ Create project works"
echo "  ✅ Retrieve project works"
echo ""
echo "Ready to test frontend UI!"
