/**
 * Configuration File Templates
 * Standard project configuration files
 */

export const packageJsonTemplate = (projectData: any): Record<string, any> => {
  const { name, projectName, specification, description, version = '1.0.0' } = projectData;
  const rawTitle = name || projectName || specification?.tournamentName || 'tournament-website';
  const safeName =
    String(rawTitle).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') ||
    'tournament-website';

  return {
    name: safeName,
    version,
    description: description || specification?.description || 'Tournament website generated by Agentic Platform',
    type: 'module',
    scripts: {
      dev: 'concurrently "vite" "tsx watch server/index.ts"',
      build: 'vite build && tsc --noEmit',
      preview: 'vite preview',
      start: 'node --loader tsx/esm server/index.ts',
      'db:push': 'drizzle-kit push:pg',
      'db:studio': 'drizzle-kit studio',
      lint: 'eslint . --ext .ts,.tsx',
      typecheck: 'tsc --noEmit'
    },
    dependencies: {
      react: '^18.2.0',
      'react-dom': '^18.2.0',
      express: '^4.18.2',
      'drizzle-orm': '^0.30.0',
      'pg': '^8.11.0',
      clsx: '^2.0.0',
      'lucide-react': '^0.292.0'
    },
    devDependencies: {
      '@types/express': '^4.17.21',
      '@types/pg': '^8.10.9',
      '@types/react': '^18.2.0',
      '@types/react-dom': '^18.2.0',
      '@types/node': '^20.0.0',
      typescript: '^5.3.0',
      vite: '^5.0.0',
      '@vitejs/plugin-react': '^4.2.0',
      'drizzle-kit': '^0.20.0',
      tsx: '^4.7.0',
      concurrently: '^8.2.0',
      tailwindcss: '^3.3.0',
      autoprefixer: '^10.4.16',
      postcss: '^8.4.31',
      eslint: '^8.54.0'
    }
  };
};

export const tsConfigTemplate = (): Record<string, any> => ({
  compilerOptions: {
    target: 'ES2020',
    useDefineForClassFields: true,
    lib: ['ES2020', 'DOM', 'DOM.Iterable'],
    module: 'ESNext',
    moduleResolution: 'bundler',
    skipLibCheck: true,
    esModuleInterop: true,
    allowSyntheticDefaultImports: true,
    strict: true,
    resolveJsonModule: true,
    isolatedModules: true,
    sourceMap: true,
    noEmit: true,
    jsx: 'react-jsx',
    baseUrl: '.',
    paths: {
      '@/*': ['./client/src/*'],
      '@server/*': ['./server/*'],
      '@shared/*': ['./shared/*']
    }
  }
});

export const viteConfigTemplate = (): string => `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  root: 'client',
  server: {
    port: 5173,
  },
  build: {
    outDir: '../dist/client',
    emptyOutDir: true,
    target: 'ES2020'
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './client/src'),
      '@server': path.resolve(__dirname, './server'),
      '@shared': path.resolve(__dirname, './shared'),
    },
  },
});
`;

export const tailwindConfigTemplate = (): string => `import type { Config } from 'tailwindcss';

export default {
  content: [
    './client/index.html',
    './client/src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#3b82f6',
        secondary: '#1e40af',
      },
    },
  },
  plugins: [],
} satisfies Config;
`;

export const dockerfileTemplate = (): string => `FROM node:20-alpine

WORKDIR /app

# Copy generated project files (devDeps needed for vite/tsx build)
COPY package*.json ./
RUN npm ci

# Build frontend and backend
COPY . .
RUN npm run build

EXPOSE 5000

CMD ["npm", "start"]
`;

export const postcssConfigTemplate = (): string => `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`;

export const envExampleTemplate = (projectData?: any): string => `# Database
DATABASE_URL=postgresql://user:password@localhost:5432/tournament_db

# Server
PORT=5000
NODE_ENV=production

# API
API_URL=http://localhost:5000

# External APIs (if needed)
# GOOGLE_SHEETS_API_KEY=
# CHESS_API_KEY=

# Session
SESSION_SECRET=your-session-secret-here
`;

export const gitignoreTemplate = (): string => `# Dependencies
node_modules/
/.pnp
.pnp.js

# Testing
/coverage

# Production
/dist
/build

# Misc
.DS_Store
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Environment variables
.env
.env.local
.env.*.local

# IDE
.vscode/
.idea/
*.swp
*.swo

 # Generated
 /generated-projects
 `;

/** Sanitize a page name into a safe TS identifier + file basename. */
export const pageFileBase = (name: string): string =>
  String(name || 'page').toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-_]/g, '') || 'page';

export const pageComponentAlias = (name: string, index: number): string => {
  const cleaned = String(name || `Page${index}`).replace(/[^a-zA-Z0-9]/g, '') || `Page${index}`;
  const pascal = cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
  return `Page_${/^[A-Za-z_$]/.test(pascal) ? pascal : `P${index}_${pascal}`}`;
};

export const clientIndexHtmlTemplate = (appTitle: string): string => `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${appTitle}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;

export const clientMainTsxTemplate = (): string => `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`;

export const clientIndexCssTemplate = (): string => `@tailwind base;
@tailwind components;
@tailwind utilities;
`;

export interface EntryPageRef {
  name: string;
  fileBase: string;
  alias: string;
}

/** App shell with tab nav over generated pages (no router dep required). */
export const appTsxTemplate = (appTitle: string, pages: EntryPageRef[]): string => {
  const imports = pages.map((p) => `import ${p.alias} from './pages/${p.fileBase}';`).join('\n');
  const buttons = pages
    .map((p, i) => `        <button
          key="${p.alias}"
          onClick={() => setActive(${i})}
          className={\`px-4 py-2 rounded-lg font-medium \` + (active === ${i} ? 'bg-blue-600 text-white' : 'text-gray-600 hover:bg-gray-100')}
        >
          ${p.name}
        </button>`)
    .join('\n');
  const cases = pages.map((p, i) => `      case ${i}: return <${p.alias} />;`).join('\n');
  const safeTitle = appTitle.replace(/</g, '&lt;').replace(/'/g, "\\'");
  return `import React, { useState } from 'react';
${imports}

export default function App() {
  const [active, setActive] = useState(0);

  const renderPage = () => {
    switch (active) {
${cases}
      default: return ${pages.length > 0 ? `<${pages[0].alias} />` : '<div />'};
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <nav className="bg-white shadow">
        <div className="max-w-7xl mx-auto px-4 py-4 flex flex-wrap gap-2 items-center">
          <span className="text-xl font-bold text-blue-600 mr-4">${safeTitle}</span>
${buttons}
        </div>
      </nav>
      <main>{renderPage()}</main>
    </div>
  );
}
`;
};

/** Minimal Express entry that mounts generated routes + serves the vite build. */
export const serverIndexTemplate = (): string => `import express from 'express';
import path from 'path';
import router from './routes/index';

const app = express();
const PORT = Number(process.env.PORT || 5000);

app.use(express.json());
app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.sendStatus(200);
  next();
});

app.get('/health', (_req, res) => res.json({ status: 'ok' }));

// Generated routes already carry the /api prefix (e.g. router.get('/api/...'))
app.use('/', router);

const distPath = path.resolve(process.cwd(), 'dist/client');
app.use(express.static(distPath));
app.get('*', (_req, res) => {
  res.sendFile(path.join(distPath, 'index.html'), (err) => {
    if (err) res.status(404).json({ error: 'Not found — run npm run build first' });
  });
});

app.listen(PORT, '0.0.0.0', () => {
  console.log(\`Server running at http://localhost:\${PORT}\`);
});

export default app;
`;

/** Drizzle + pg connection shared by all generated routes. */
export const dbClientTemplate = (): string => `import { Pool } from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import * as schema from './schema';

const pool = new Pool({
  connectionString: process.env.DATABASE_URL || 'postgresql://user:password@localhost:5432/tournament_db',
});

export const db = drizzle(pool, { schema });
export default db;
`;

export const sharedTypesTemplate = (spec: any): string => {  const s = spec ?? {};
  return `/** Shared types for ${s.tournamentName || 'the tournament website'} (generated). */

export interface Tournament {
  id: string;
  name: string;
  date: string;
  location: string;
  description?: string;
  participants?: number;
  rounds?: number;
}

export interface Participant {
  id: string;
  email: string;
  rating?: number;
  tournament_id?: string;
  registered_at?: string;
}

export interface Match {
  round: number;
  date: string;
  startTime?: string;
  description?: string;
}

export interface GenerationSpec {
  tournamentName: string;
  date: string;
  location: string;
  description?: string;
  pages?: string[];
}
`;
};

export const apiClientTemplate = (): string => `/** Typed fetch helpers for the generated API. */

const BASE = (import.meta as any).env?.VITE_API_URL || '';

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const res = await fetch(\`\${BASE}\${path}\`, {
    headers: { 'Content-Type': 'application/json' },
    ...init,
  });
  if (!res.ok) {
    const body = await res.json().catch(() => ({}));
    throw new Error((body as any).error || \`Request failed: \${res.status}\`);
  }
  return res.json() as Promise<T>;
}

export const api = {
  getTournament: () => request('/api/tournament'),
  getParticipants: () => request('/api/participants'),
  getSchedule: () => request('/api/schedule'),
  register: (payload: { email: string; rating?: number }) =>
    request('/api/register', { method: 'POST', body: JSON.stringify(payload) }),
};
`;

