/**
 * Site Preview Builder
 * Generates a self-contained static preview page for every assembled project
 * so generated sites are instantly viewable/hostable with zero build step.
 * The full source project remains available via ZIP download.
 */

function esc(value: unknown): string {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function buildPreviewHtml(projectName: string, spec: any): string {
  const s = spec ?? {};
  const name = esc(s.tournamentName || projectName);
  const date = esc(s.date || "TBA");
  const location = esc(s.location || "TBA");
  const description = esc(s.description || "Tournament website generated by Agentic Platform");
  const pages: string[] = Array.isArray(s.pages) ? s.pages : ["home", "register", "schedule"];
  const participants = esc(s.numberOfParticipants ?? "—");
  const rounds = esc(s.rounds ?? "—");
  const format = esc(s.matchFormat || "—");

  const pageCards = pages
    .map(
      (p) => `
        <div class="bg-white rounded-xl shadow p-6 text-left">
          <div class="text-xs font-semibold uppercase tracking-wide text-blue-600">${esc(p)}</div>
          <h3 class="mt-1 text-lg font-bold capitalize">${esc(p)} page</h3>
          <p class="mt-1 text-sm text-gray-500">Included in the generated source (download the ZIP for full code).</p>
        </div>`
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${name}</title>
<script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-50 text-gray-900">
  <header class="bg-gradient-to-r from-blue-700 to-indigo-800 text-white">
    <div class="max-w-5xl mx-auto px-6 py-16 text-center">
      <p class="text-sm uppercase tracking-widest text-blue-200">Tournament Website · Live Preview</p>
      <h1 class="mt-2 text-4xl md:text-5xl font-extrabold">${name}</h1>
      <p class="mt-3 text-lg text-blue-100">${description}</p>
      <div class="mt-6 flex flex-wrap justify-center gap-3 text-sm">
        <span class="bg-white/15 rounded-full px-4 py-1.5">📅 ${date}</span>
        <span class="bg-white/15 rounded-full px-4 py-1.5">📍 ${location}</span>
        <span class="bg-white/15 rounded-full px-4 py-1.5">👥 ${participants} players</span>
        <span class="bg-white/15 rounded-full px-4 py-1.5">🏁 ${rounds} rounds · ${format}</span>
      </div>
      <a href="#pages" class="mt-8 inline-block bg-white text-blue-700 font-semibold px-8 py-3 rounded-lg hover:bg-blue-50">Explore Pages</a>
    </div>
  </header>
  <main class="max-w-5xl mx-auto px-6 py-12">
    <h2 id="pages" class="text-2xl font-bold mb-6">Generated pages (${pages.length})</h2>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">${pageCards}</div>
    <div class="mt-10 bg-white rounded-xl shadow p-6">
      <h3 class="text-lg font-bold">About this preview</h3>
      <p class="mt-2 text-sm text-gray-600">This is the instant static preview generated with your site. The complete React + Express + PostgreSQL source code is available as a ZIP download from your project dashboard, and can be deployed to Vercel or any host.</p>
    </div>
  </main>
  <footer class="text-center text-xs text-gray-400 py-6">Generated by Agentic Platform · ${esc(projectName)}</footer>
</body>
</html>`;
}
